
services:
  spark:
    build: .
    container_name: python
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8501:8501"
    volumes:
      - ./app:/opt/spark/app
      - ./drivers:/opt/spark/jars
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/opt/bitnami/spark
    depends_on:
      - postgres
    networks:
      - python-postgres


  postgres:
    image: "postgres:latest"
    container_name: postgres-database
    ports:
    - "5442:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_engsr_desafio
    networks:
      - python-postgres

volumes:
  postgres:

networks:
  python-postgres:
